{{- if .Values.backend.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrag.fullname" . }}-aws
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.backend.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.backend.aws.secretAccessKey | quote }}
{{- end }}
