{{- if .Values.global.opensearch.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrag.fullname" . }}-opensearch
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.global.opensearch.password | quote }}
  username: {{ .Values.global.opensearch.username | quote }}
{{- end }}
