{{- if .Values.langflow.flows.loadDefaults }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openrag.fullname" . }}-flow-agent
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
data:
  openrag_agent.json: |-
{{ .Files.Get "flows/openrag_agent.json" | indent 4 }}
{{- end }}
