{{- if .Values.langflow.flows.loadDefaults }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openrag.fullname" . }}-flow-ingestion
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
data:
  ingestion_flow.json: |-
{{ .Files.Get "flows/ingestion_flow.json" | indent 4 }}
{{- end }}
